[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing - this must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
